config/routes.rb
Billguru::Application.routes.draw do

  resources :payments

  resources :reminders

  resources :users

  resources :sessions,      :only => [:new, :create, :destroy]

  root :to => "pages#home"
  
  match '/summary', :to => 'payments#summary'
  match '/report', :to => 'payments#report'
  match '/analysis', :to => 'payments#analysis'

  match '/contact', :to => 'users#contact'
  match '/phone', :to => 'pages#phone'
  match '/verify_phone', :to => 'pages#verify_phone'
  match '/activate_account/:token', :to => 'users#activate'

  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/help',    :to => 'pages#help'
  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/search',  :to => 'users#search'

end

app/models/user.rb
# == Schema Information
# Schema version: 20100829021049
#
# Table name: users
#
#  id                 :integer         not null, primary key
#  name               :string(255)
#  email              :string(255)
#  created_at         :datetime
#  updated_at         :datetime
#  encrypted_password :string(255)
#  salt               :string(255)
#  admin              :boolean
#

class User < ActiveRecord::Base
  attr_accessor   :password
  attr_accessible :name, :email, :password, :password_confirmation, :photo
  
  has_many :microposts,    :dependent => :destroy
  has_many :relationships, :dependent => :destroy,
                           :foreign_key => "follower_id"
  has_many :reverse_relationships, :dependent => :destroy,
                                   :foreign_key => "followed_id",
                                   :class_name => "Relationship"
  has_many :following, :through => :relationships, :source => :followed
  has_many :followers, :through => :reverse_relationships,
                       :source  => :follower

  has_many :reminders,    :dependent => :destroy
  has_one :token

  #paperclip
  has_attached_file :photo
  #,
  #   :styles => {
  #     :thumb=> "100x100#",
  #     :small  => "400x400>" }

  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  
  validates :name,  :presence => true,
                    :length   => { :maximum => 50 }
  validates :email, :presence   => true,
                    :format     => { :with => email_regex },
                    :uniqueness => { :case_sensitive => false }
  validates :password, :presence => true,
                       :confirmation => true,
                       :length => { :within => 6..40 }

  before_save :encrypt_password
  
  def has_password?(submitted_password)
    encrypted_password == encrypt(submitted_password)
  end
  
  def feed
    Micropost.from_users_followed_by(self)
  end
  
  def following?(followed)
    relationships.find_by_followed_id(followed)
  end
  
  def follow!(followed)
    relationships.create!(:followed_id => followed.id)
  end
  
  def unfollow!(followed)
    relationships.find_by_followed_id(followed).destroy
  end

  def confirmed!
    self.confirmed = true
    self.confirmation_token = nil
    save(false) 
  end


  class << self
    def authenticate(email, submitted_password)
      user = find_by_email(email)
      (user && user.has_password?(submitted_password)) ? user : nil
    end
    
    def authenticate_with_salt(id, cookie_salt)
      user = find_by_id(id)
      (user && user.salt == cookie_salt) ? user : nil
    end
  end
  
  private
  
    def encrypt_password
      self.salt = make_salt unless has_password?(password)
      self.encrypted_password = encrypt(password)
    end
  
    def encrypt(string)
      secure_hash("#{salt}--#{string}")
    end
    
    def make_salt
      secure_hash("#{Time.now.utc}--#{password}")
    end
    
    def secure_hash(string)
      Digest::SHA2.hexdigest(string)
    end



end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate, :only => [:index, :edit, :update, :destroy]
  before_filter :correct_user, :only => [:edit, :update]
  before_filter :admin_user,   :only => :destroy
  
  def index
    if params[:search_user]
        @users = User.paginate :per_page => 10, :page => params[:page],:conditions => ["name like ?","#{params[:search_user]}%"], :order => 'name ASC'
	if @users.blank?
	      flash.now[:error] = "User not Found."
	end
    else
	@users = User.paginate(:page => params[:page],:per_page => 10)
    end
    @title = "All users"
  end

  def search

  end

  def show
    @user = User.find(params[:id])
    #@microposts = @user.microposts.paginate(:page => params[:page],:per_page => 5)
    @title = @user.name
  end

  def following
    @title = "Following"
    @user = User.find(params[:id])
    @users = @user.following.paginate(:page => params[:page])
    render 'show_follow'
  end
  
  def followers
    @title = "Followers"
    @user = User.find(params[:id])
    @users = @user.followers.paginate(:page => params[:page])
    render 'show_follow'
  end

  def new
    @user  = User.new
    @title = "Sign up"
  end
  
  def create
    @user = User.new(params[:user])
    #@user.confirmation_token = generate_activation_code(20)
    if @user.save
      #sign_in @user
      #Token.new({:activation_tokn => generate_activation_code(20),:user_id => @user.id})
      @token = Token.new
      @token.activation_tokn = generate_activation_code(20)
      @token.user_id = @user.id
      @token.save
      Notification.deliver_activate_user(@user) 
      redirect_to root_path, :flash => { :success => "Registration completed successfully. Activation link sent to your email id" }
    else
      @title = "Sign up"
      render 'new'
    end
  end
  
  def edit
    @title = "Edit user"
  end
  
  def update
    if @user.update_attributes(params[:user])
      redirect_to root_path, :flash => { :success => "Profile updated. Please login again to continue" }
    else
      @title = "Edit user"
      render 'edit'
    end
  end

  def destroy
    @user.destroy
    redirect_to users_path, :flash => { :success => "User destroyed." }
  end

  def activate
    puts "activate account ---------> "
    puts params[:token]
    token = Token.find(:first, :conditions => {:activation_tokn => params[:token]})
    if (!params[:token].blank?) && token && !token.user_active?
       #user.confirmed!
       #self.current_user = user
	token.update_attributes(:user_active => true, :activation_tokn => '')
       sign_in token.user
       redirect_to root_path, :flash => { :success => "Thank you. You account is now activated." }
   else
      redirect_to root_path, :flash => { :error => "Sorry something went wrong." }
   end
  end
	
  private

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_path) unless current_user?(@user)
    end
    
    def admin_user
      @user = User.find(params[:id])
      redirect_to(root_path) if !current_user.admin? || current_user?(@user)
    end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, options = { :size => 50 })
    gravatar_image_tag(user.email.downcase, :alt => h(user.name),
                                            :class => 'gravatar',
                                            :gravatar => options)
  end
end

app/views/users/_fields.html.erb
<div class="field">
  <%= f.label :name %><br />
  <%= f.text_field :name %>
</div>
<div class="field">
  <%= f.label :email %><br />
  <%= f.text_field :email %>
</div>
<div class="field">
  <%= f.label :password %><br />
  <%= f.password_field :password %>
</div>
<div class="field">
  <%= f.label :password_confirmation, "Confirmation" %><br />
  <%= f.password_field :password_confirmation %>
</div>

app/views/users/_follow.html.erb
<%= form_for(current_user.relationships.
                          build(:followed_id => @user.id),
                          :remote => true) do |f| %>
  <div><%= f.hidden_field :followed_id %></div>
  <div class="actions"><%= f.submit "Follow" %></div>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
  <div id="follow_form">
    <% if current_user.following?(@user) %>
      <%= render 'unfollow' %>
    <% else %>
      <%= render 'follow' %>
    <% end %>
  </div>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.relationships.find_by_followed_id(@user),
             :html => { :method => :delete },
             :remote => true) do |f| %>
  <div class="actions"><%= f.submit "Unfollow" %></div>
<% end %>

app/views/users/_user.html.erb
<li>
  <%= link_to user.name, user %>
  <% if current_user.admin? %>
  |
  <%= link_to "delete", user, :method => :delete, :confirm => "You sure?",
                              :title => "Delete #{user.name}" %>
  <% end %>
</li>

app/views/users/contact.html.erb
<script type="text/javascript">
function numbersonly(e,value){
var unicode=e.charCode? e.charCode : e.keyCode
if (unicode!=8){ //if the key isn't the backspace key (which we should allow)
if (unicode<48||unicode>57) //if not a number
return false //disable key press
}
}

function xxx(){
var x=10;
alert();
//var x=document.getElementById('phone_no').value;
alert(x);
if (x==null || x=="")
  {
  alert("First name must be filled out");
  return false;
  }
}
</script>


<h1>Mobile No</h1>
<div id="phone">
    <form name="phone_form" action="/phone" method="post">
<p>(enter and verify your mobile no to receive alert from BillGuru)</p>
	<input id="pnone_no" autocomplete="off" type="text" placeholder="Phone No" onkeypress="return numbersonly(event,this.value)" name="pnone_no" size="15" />
	<input id="phone_button" type="submit" value="Submit"/>
    </form>
<div>

       <% if current_user.token.phone_active %>
	    <div style="padding-top:7px;float:left">Status : Verified </div>
            <div style="padding-top:5px;padding-left:10px;float:left"> <img src="images/icons/true_stat.png" alt="True"/></div>
            <div style="padding-top:7px;padding-left:10px;float:left"> <b>(phone no: <%= current_user.token.phone_no %>)</b> </div>
       <% else %>	  
	    <div style="padding-top:7px;float:left">Status : Not verified</div>
            <div style="padding-top:5px;padding-left:10px;float:left"> <img src="images/icons/false_stat.png" alt="False"/></div>
       <% end %>

</div>
</div>
<br/>
<br/>
<h1>Verify Mobile No</h1>
<div>
    <form name="phone_form" action="/verify_phone" method="get">
<p>(enter the verification code which you received from BillGuru)</p>
	<input id="verify_no" autocomplete="off" type="text" placeholder="Verification Code" name="verify_no" size="15" />
	<input id="phone_button" type="submit" value="Verify" />
    </form>

</div>

app/views/users/edit.html.erb
<h1>My Profile</h1>

<%= form_for(@user) do |f| %>
  <%= render 'shared/error_messages', :object => f.object %>
  <%= render 'fields', :f => f %>
  <div class="actions">
    <%= f.submit "Update" %>
  </div>
<% end %>

app/views/users/index.html.erb
<div id="search_container" style="display:inline;">
<div style="width:200px;">
<h1>All users</h1>
</div>
<div id="search_project_container" style="width:240px;float:right">
    <form name="search_form" action="/users" method="get">
	<input id="search_input_project" autocomplete="off" type="text" placeholder="Search User" name="search_user" size="20" value="<%= params[:search_user] %>"/>
	<input id="search_user_button" type="submit" value="Search" />
    </form>
</div>
</div>

<ul class="users">
  <%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<h1>Sign up</h1>

<%= form_for @user,:html => { :multipart => true } do |f| %>
  <%= render 'shared/error_messages', :object => f.object %>
  <%= render 'fields', :f => f %>
  <div class="actions">
    <%= f.submit "Sign up" %>
  </div>  
<% end %>

app/views/users/show.html.erb
<h1>Settings</h1>
<br/>
<ul>
  <li><b><%= link_to 'Contact No', contact_path %></b></li>
  <li><b><%= link_to 'Payment Summary', summary_path %></b></li>
  <li><b><%= link_to 'Payment Report', report_path %></b></li>
  <li><b><%= link_to 'Spend Analysis', analysis_path %></b></li>
</ul>
<br/>

app/views/users/show_follow.html.erb
<table summary="Information about following/followers">
  <tr>
    <td class="main">
      <h1><%= @title %></h1>
      
      <% if @users.any? %>
        <ul class="users">
          <%= render @users %>
        </ul>  
        <%= will_paginate @users %>
      <% end %>
    </td>
    <td class="sidebar round">
      <strong>Name</strong> <%= @user.name %><br />
      <strong>URL</strong> <%= link_to user_path(@user), @user %><br />
      <strong>Microposts</strong> <%= @user.microposts.count %>
      <%= render 'shared/stats' %>
      <% if @users.any? %>
        <% @users.each do |user| %>
          <%= link_to gravatar_for(user, :size => 30), user %>
        <% end %>
      <% end %>
    </td>
  </tr>
</table>

app/views/users/verify_mobile.html.erb
<h1>Verify Mobile No</h1>
<div>
    <form name="phone_form" action="/verify_phone" method="get">
	<input id="verify_no" autocomplete="off" type="text" placeholder="Verification Code" name="verify_no" size="10" />
	<input id="phone_button" type="submit" value="Submit" />
    </form>
<p>Status : Not verified</p>
</div>