config/routes.rb
Billguru::Application.routes.draw do

  resources :payments

  resources :reminders

  resources :users

  resources :sessions,      :only => [:new, :create, :destroy]

  root :to => "pages#home"
  
  match '/summary', :to => 'payments#summary'
  match '/report', :to => 'payments#report'
  match '/analysis', :to => 'payments#analysis'

  match '/contact', :to => 'users#contact'
  match '/phone', :to => 'pages#phone'
  match '/verify_phone', :to => 'pages#verify_phone'
  match '/activate_account/:token', :to => 'users#activate'

  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/help',    :to => 'pages#help'
  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/search',  :to => 'users#search'

end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(object.errors.count, "error") %>
      prohibited this <%= object.class.to_s.underscore.humanize.downcase %>
      from being saved:
    </h2>
    <p>There were problems with the following fields:</p>
    <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
  
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <table class="microposts" summary="Status feed">
    <%= render :partial => 'shared/feed_item', :collection => @feed_items %>
  </table>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_feed_item.html.erb
<tr>
  <td class="gravatar">
    <%= link_to gravatar_for(feed_item.user), feed_item.user %>
  </td>
  <td class="micropost">
    <span class="user">
      <%= link_to feed_item.user.name, feed_item.user %>
    </span>
    <span class="content"><%= wrap(feed_item.content) %></span>
    <span class="timestamp">
      Posted <%= time_ago_in_words(feed_item.created_at) %> ago.
    </span>
  </td>
  <% if current_user?(feed_item.user) %>
    <td>
      <%= link_to "delete", feed_item, :method => :delete,
                                       :confirm => "You sure?",
                                       :title => feed_item.content %>
    </td>
  <% end %>
</tr>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>
  <%= render 'shared/error_messages', :object => f.object %>
  <div class="field">
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit "Submit" %>
  </div>
<% end %>

app/views/shared/_payment_item.html.erb
<table id="customers" style="width:500px">
  <tr>
    <th>Pay date</th>
    <th>Amount</th>
    <th>Notes</th>
    <th colspan="3">Action</th>
  </tr>
<% total = 0 %>
<% @payments.each do |payment| %>
  <tr>
    <td style="text-align:center"><%= payment.pay_date %></td>
    <td style="text-align:center"><%= payment.amount %></td>
    <td><%= payment.notes %></td>
    <td><%= link_to 'Show', payment %></td>
    <td><%= link_to 'Edit', edit_payment_path(payment) %></td>
   </tr>
   <% total += payment.amount.to_i %>
<% end %>
  <% if show_total == true %>
    <tr>
    <td style="text-align:center"><b>Total Amount</b></td>
    <td style="text-align:center"><b><%= total %></b></td>
  </tr>
  <% end %>
</table>
<br/>

app/views/shared/_payment_report_item.html.erb
<table id="customers" style="width:500px">
  <tr>
    <th>Reminder</th>
    <th>Payment Date</th>
    <th>Amount</th>
    <th>Notes</th>
    <th colspan="3">Action</th>
  </tr>
<% total = 0 %>
<% @payments.each do |payment| %>
  <% unless payment.reminder.nil? %>
      <tr>
        <td style="text-align:center"><%= payment.reminder.description %></td>
        <td style="text-align:center"><%= payment.pay_date %></td>
        <td style="text-align:center"><%= payment.amount %></td>
        <td><%= payment.notes %></td>
        <td><%= link_to 'Show', payment %></td>
        <td><%= link_to 'Edit', edit_payment_path(payment) %></td>
       </tr>
       <% total += payment.amount.to_i %>
   <% end %>
<% end %>
  <% if show_total == true %>
   <tr>
    <td style="text-align:center"></td>
    <td style="text-align:center"><b>Total Amount</b></td>
    <td style="text-align:center"><b><%= total %></b></td>
    <td style="text-align:center"></td>
    <td style="text-align:center"></td>
    <td style="text-align:center"></td>
  </tr>
  <% end %>
</table>
<br/>

app/views/shared/_reminder_item.html.erb
<table id="customers">
  <tr>
    <th width="25%" align="left" >Bill Title</th>
    <th width="15%" align="left" >Alert Type</th>
    <th width="10%" align="left" >Next Due date</th>
    <th>Alert threshold</th>
    <th>Email</th>
    <th>Sms</th>
    <th>Facebook</th>
    <th colspan="3">Action</th>
  </tr>

<% for reminder in @reminders %>  
<tr class="<%= cycle("even", "alt") %>">
    <td width="20%"><%= link_to truncate(reminder.description, {:length => 30,:omission => '...'}) , reminder%> </td>
    <td width="10%"><%= alert_type_name(reminder.alert_type.to_i) %></td>
    <td width="10%"><%= reminder.due_date %></td>
    <td width="5%"><%= reminder.alert_threshold %> Day(s)</td>
    <td width="5%" style="text-align:center">
       <% if reminder.email %>
	    <img src="images/icons/tick.png" alt="True"/>
       <% else %>	  
	    <img src="images/icons/cross.png" alt="False"/>
       <% end %>
    </td>
    <td width="5%" style="text-align:center">
       <% if reminder.sms %>
	    <img src="images/icons/tick.png" alt="True"/>
       <% else %>	  
	    <img src="images/icons/cross.png" alt="False"/>
       <% end %>
    </td>
    <td width="5%" style="text-align:center">
       <% if reminder.facebook %>
	    <img src="images/icons/tick.png" alt="True"/>
       <% else %>	  
	    <img src="images/icons/cross.png" alt="False"/>
       <% end %>
    </td>
    <td><%= link_to 'Edit', edit_reminder_path(reminder) %></td>
    <td><%= link_to 'Destroy', reminder, :confirm => 'Are you sure?', :method => :delete %></td>
    <td><%= link_to 'Paid', new_payment_path(:bill_id => reminder.id) %></td>
  </tr>
<% end %>

</table>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <table summary="User stats">
    <tr>
      <td>
        <a href="<%= following_user_path(@user) %>">
          <span id="following" class="stat">
            <%= @user.following.count %> following
          </span>
        </a>
      </td>
      <td>
        <a href="<%= followers_user_path(@user) %>">
          <span id="followers" class="stat">
            <%= pluralize(@user.followers.count, "follower") %>
          </span>
        </a>
      </td>
    </tr>
  </table>
</div>

app/views/shared/_user_info.html.erb
<div class="user_info">
  <a href="<%= user_path(current_user) %>">
        <span class="user_name">
      <%= current_user.name %>
    </span>

  </a>
</div>