config/routes.rb
Billguru::Application.routes.draw do

  resources :payments

  resources :reminders

  resources :users

  resources :sessions,      :only => [:new, :create, :destroy]

  root :to => "pages#home"
  
  match '/summary', :to => 'payments#summary'
  match '/report', :to => 'payments#report'
  match '/analysis', :to => 'payments#analysis'

  match '/contact', :to => 'users#contact'
  match '/phone', :to => 'pages#phone'
  match '/verify_phone', :to => 'pages#verify_phone'
  match '/activate_account/:token', :to => 'users#activate'

  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/help',    :to => 'pages#help'
  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/search',  :to => 'users#search'

end

app/models/payment.rb
class Payment < ActiveRecord::Base
   belongs_to :reminder

  def self.send_notifications
    logger.info "hi this is from whenever gem -------->"
    logger.info Time.now.tologger_s
  end
end

app/controllers/payments_controller.rb
require 'rubygems'
require 'google_chart'

class PaymentsController < ApplicationController
before_filter :authenticate

  # GET /payments
  # GET /payments.xml
  def index
    @payments = Payment.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @payments }
    end
  end

  # GET /payments/1
  # GET /payments/1.xml
  def show
    @payment = Payment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @payment }
    end
  end

  # GET /payments/new
  # GET /payments/new.xml
  def new
    @payment = Payment.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @payment }
    end
  end

  # GET /payments/1/edit
  def edit
    @payment = Payment.find(params[:id])
  end

  # POST /payments
  # POST /payments.xml
  def create
    @payment = Payment.new(params[:payment])
    @payment.user_id = current_user.id
p "testing here 11111 ----"
p params[:payment][:reminder_id]


	    @reminder = Reminder.find_by_id(params[:payment][:reminder_id])
#p @reminder.alert_type
p @reminder
	    if @reminder.alert_type == "1"
		p "weekly ----"
		@reminder.due_date = @reminder.due_date+7.days
	    elsif @reminder.alert_type == "2"
		p "monthly ----"
		@reminder.due_date = @reminder.due_date+1.month
	    elsif @reminder.alert_type == "3"
		p "two months ----"
		@reminder.due_date = @reminder.due_date+2.month
	    elsif @reminder.alert_type == "0"
		p "one day ----"
		@reminder.due_date = @reminder.due_date+1.day
	    end
	    @reminder.save
    respond_to do |format|
      if @payment.save

        format.html { redirect_to(@payment.reminder, :notice => 'Payment was successfully created.') }
        format.xml  { render :xml => @payment, :status => :created, :location => @payment }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @payment.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /payments/1
  # PUT /payments/1.xml
  def update
    @payment = Payment.find(params[:id])

    respond_to do |format|
      if @payment.update_attributes(params[:payment])
        format.html { redirect_to(@payment, :notice => 'Payment was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @payment.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /payments/1
  # DELETE /payments/1.xml
  def destroy
    @payment = Payment.find(params[:id])
    @payment.destroy

    respond_to do |format|
      format.html { redirect_to :back}
      format.xml  { head :ok }
    end
  end

  def summary
    @title = "Payment Summary"
    @reminders = current_user.reminders
  end

  def report
    @title = "Payment Report"
    @reminders = current_user.reminders
    p "payment Report ------"
    p @reminders
      if params[:start]
        p @start_date = Date.civil(params[:start][:"start_date(1i)"].to_i,params[:start][:"start_date(2i)"].to_i,params[:start][:"start_date(3i)"].to_i)
        p @end_date = Date.civil(params[:end][:"start_date(1i)"].to_i,params[:end][:"start_date(2i)"].to_i,params[:end][:"start_date(3i)"].to_i)


#ids = LevelsQuestion.all(:select => "question_id", :conditions => "level_id = 15").collect(&:question_id)
#Question.all(:select => "id, name", :conditions => ["id not in (?)", ids])
p "the ids val is ------------"
ids = Reminder.all(:select => "id", :conditions => "user_id = #{current_user.id}").collect(&:id)
p ids
        #report generation
          @payments = Payment.paginate :per_page => 100,
                                       :page => params[:pay_page],
                                       :conditions => ["user_id = ? and pay_date between ? and ? ", current_user.id, "#{@start_date}%", "#{@end_date}%"], :order => 'pay_date DESC'
                                       #:conditions => ["title like ? and date between ? and ?","%#{@query_news}%", "#{@start_date}%", "#{@end_date}%"], :order => 'title ASC'
          if @payments.empty?
           flash.now[:notice] = 'No payments found in the given date range.'
          else
            p "pay length "
            p @payments.length
          end
      end
    end

  def analysis
    GoogleChart::PieChart.new('600x300', "Pie Chart",false) do |pc|

       current_user.reminders.each { |reminder|
              @total = 0
              reminder.payments.each { |payment|
                 @total+= payment.amount
              }
              p "#{reminder.description} , #{@total}"
              pc.data reminder.description.to_s , @total.to_i
              
       }
      #pc.data "Apples", 40
      #pc.data "Banana", 20
      #pc.data "Peach", 30
      #pc.data "Orange", 60
      pc.is_3d = true
      puts "\nPie Chart"
      puts pc.to_url
      # Pie Chart with no labels
      pc.show_labels = true
      puts "\nPie Chart (with no labels)"
      puts pc.to_url
      p @chart_url =  pc.to_url
    end
  end
  
end

app/helpers/payment_helper.rb
module PaymentHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/payments/_form.html.erb
<%= form_for(@payment) do |f| %>
  <% if @payment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@payment.errors.count, "error") %> prohibited this payment from being saved:</h2>

      <ul>
      <% @payment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<% if !params[:bill_id].nil? %>
  <%= f.hidden_field :reminder_id, :value => params[:bill_id] %>
<% else %>
 <%= f.hidden_field :reminder_id, :value => @payment.reminder.id %>
<% end %>
  <div class="field">
    <%= f.label :pay_date %><br />
    <%= f.date_select :pay_date %>
  </div>
  <div class="field">
    <%= f.label :amount %><br />
    <%= f.text_field :amount %>
  </div>
  <div class="field">
    <%= f.label :notes %><br />
    <%= f.text_area :notes %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/payments/analysis.html.erb
<html>
  <head>

  </head>
  <body>
    <h1>Spending Analysis - By Bill</h1>
    <div id="chart_div1" style="width: 900px; height: 500px;text-align:center;margin-top: 100px;">
      <img src="<%= @chart_url %> " />
    </div>

  </body>
</html>

app/views/payments/edit.html.erb
<h1>Editing payment</h1>

<%= render 'form' %>

<%= link_to 'Show', @payment %> |
<%= link_to 'Back', reminder_path(@payment.reminder) %>

app/views/payments/index.html.erb
<h1>Listing payments</h1>

<table>
  <tr>
    <th>Reminder</th>
    <th>Pay date</th>
    <th>Amount</th>
    <th>Notes</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @payments.each do |payment| %>
  <tr>
    <td><%= payment.reminder_id %></td>
    <td><%= payment.pay_date %></td>
    <td><%= payment.amount %></td>
    <td><%= payment.notes %></td>
    <td><%= link_to 'Show', payment %></td>
    <td><%= link_to 'Edit', edit_payment_path(payment) %></td>
    <td><%= link_to 'Destroy', payment, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Payment', new_payment_path %>

app/views/payments/new.html.erb
<h1>New payment</h1>

<%= render 'form' %>

<%= link_to 'Back', payments_path %>

app/views/payments/report.html.erb
<h1>Payment Report</h1>
<form name="report_form" action="/report" method="get">
  <% if not params[:start].nil? %>
    <% @start_date = Date.civil(params[:start][:"start_date(1i)"].to_i,params[:start][:"start_date(2i)"].to_i,params[:start][:"start_date(3i)"].to_i) %>
  <% end %>
  <% if not params[:end].nil? %>
    <% @end_date = Date.civil(params[:end][:"start_date(1i)"].to_i,params[:end][:"start_date(2i)"].to_i,params[:end][:"start_date(3i)"].to_i) %>
  <% end %>
  <% if @start_date.nil? %>
    <% @start_date = Date.today %>
  <% end %>
  <% if @end_date.nil? %>
    <% @end_date = Date.today + 10.days %>
  <% end %>

      <fieldset class="form_option">
          <legend>Options</legend>
          <table>
          <tr>
          <td></td>
          <td align="left" ><b>From :</b> <%= date_select('start', 'start_date', :order => [:month, :day, :year],:default => @start_date )%>
          </td>
          <td></td>
          <td align="left" ><b>&nbsp;&nbsp;&nbsp;&nbsp;To:</b> <%= date_select('end', 'start_date', :order => [:month, :day, :year],:default => @end_date)%></td>
          <td></td>
          <td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input id="generate" type="submit" value="Generate Report" /></td>
          </tr>
          </table>
          
      </fieldset>

</form>



<% if !@payments.blank? %>
	<h1>Payments</h1>
	<%= render :partial => 'shared/payment_report_item',:locals => {:show_total => true} -%>
	<%= will_paginate @payments %>
<% end %>

app/views/payments/show.html.erb
<h1>Payment Detail</h1>



<table>
<tr>
<td><b>Pay date:</b></td>
<td><%= @payment.pay_date %></td>
</tr>

<tr>
<td><b>Amount:</b></td>
<td><%= @payment.amount %></td>
</tr>

<tr>
<td><b>Notes:</b></td>
<td><%= @payment.notes %></td>
</tr>

</table>
<br/>

<%= link_to 'Back', @payment.reminder %>

app/views/payments/summary.html.erb
<p id="notice"><%= notice %></p>

<h1>Payment Summary</h1>

<% if !@reminders.blank? %>
                   <% @reminders.each { |reminder| %>
                          <h4><%= reminder.description %> </h4>
                             <% if !reminder.payments.blank? %>
                                
                                <% @payments = reminder.payments.paginate(:page => params[:page],:per_page => 10) %>
                                <%= render :partial => 'shared/payment_item',:locals => {:show_total => true} -%>
                                <%= will_paginate @payments %>
                           <% else %>
                              <p> No payment availabale</P>
                           <% end %>
                   <% } %>
<% else %>
	<p> No reminders availabale</p>
<% end %>